### ISSUE TITLE
Character encoding problem

### ISSUE THREAD

**Issue by pchampin** [sympozer/sympozer-client-seed-v2#7]
Not sure whether this is an app or dataset problem, but accents are not rendered correctly.
E.g.:
* [here (Univérsité)](http://sympozer.liris.cnrs.fr/www2018/#/person/Pierre-Antoine%20Champin/https%253A%252F%252Fw3id.org%252Fscholarlydata%252Fperson%252Fpierre-antoine-champin)
* [here (Jérôme)](http://sympozer.liris.cnrs.fr/www2018/#/organization/INRIA/https%253A%252F%252Fw3id.org%252Fscholarlydata%252Forganisation%252Finria)

**Comment by lmedini** [comment]
This comes from the dataset. Moving the issue to the appropriate repo...

Lionel.
